### ISSUE TITLE
Template: When switching activity bar item icon state, it becomes another icon

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-figma-toolkit#3]
Ref: https://github.com/microsoft/vscode/issues/85978

- Start from Sample extension template
- Change the currently active icon's state from `active` to `default`
- I expect the icon to become grayed-out
- The icon becomes greyed-out AND changes into another icon

![image](https://user-images.githubusercontent.com/4033249/70097104-7a2dd080-15dd-11ea-9d8e-6fdfeb6bf765.png)

![image](https://user-images.githubusercontent.com/4033249/70097117-7dc15780-15dd-11ea-85c4-014505842130.png)

**Comment by misolori** [comment]
This must've been a Figma quirk, I reset that component instance and tested out the steps you had and it has appeared to work now.
