### ISSUE TITLE
Tab icon / title are not aligned

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-figma-toolkit#4]
Ref: https://github.com/microsoft/vscode/issues/85978

- Use Sample extension template
- See icons do not align horizontally with text

![image](https://user-images.githubusercontent.com/4033249/70098513-fd045a80-15e0-11ea-863a-bd4b57637d1a.png)

**Comment by octref** [comment]
Actual: 

![image](https://user-images.githubusercontent.com/4033249/70098538-17d6cf00-15e1-11ea-865c-f26978b79547.png)

**Comment by misolori** [comment]
Tab icons are now centered:

![image](https://user-images.githubusercontent.com/35271042/70171996-ae100100-1684-11ea-88d2-1ffe8f77de20.png)
