### ISSUE TITLE
May i ask a question not related to any issue ?

### ISSUE THREAD

**Issue by AntonGrekov** [microsoft/vscode-figma-toolkit#5]
Hi all, I am struggling to know more about this toolkit. Sorry for creating an issue. 

I used Figma for a while and i love VSCode. I see that his toolkit is about VSCode components, their visual appearance. But can this toolkit then integrate changes to a compiled VSCode theme ? I haven't found any info on that. Or is it just a graphical helper for theme creators ? 

Thanks a lot :)

**Comment by misolori** [comment]
This toolkit is intended to help extension authors design their extension experiences by re-using existing components. This does not help with creating themes, though that would be an interesting to solve for.
