### ISSUE TITLE
Extension component

### ISSUE THREAD

**Issue by jsjoeio** [microsoft/vscode-figma-toolkit#6]
Hi there! 

Thanks so much for making this toolkit for the community ♥️ I can't tell you how helpful it's been.

I would like to make a feature request: an extension component

<img width="375" alt="image" src="https://user-images.githubusercontent.com/3806031/102661019-43b7ea80-4139-11eb-9286-2236697f43b4.png">

It would help my workflow (and hopefully a bunch of other people too!) 🙏

**Comment by miguelsolorio** [comment]
We now have this on the public toolkit: https://www.figma.com/community/file/786632241522687494

<img width="914" alt="CleanShot 2021-12-13 at 11 00 20@2x" src="https://user-images.githubusercontent.com/35271042/145871948-900e7767-e659-4fda-ab89-c32769d7bd7f.png">
