### ISSUE TITLE
Broken documentation links @ Figma

### ISSUE THREAD

**Issue by listopad** [microsoft/vscode-figma-toolkit#7]
Hi there! 

I'm not sure where to write about it. This looks like a relevant place for :)

The link to the documentation ([https://aka.ms/fluent](https://aka.ms/fluent)), found in the description of Microsoft Fluent projects, sends to a 404 page.

https://www.figma.com/community/file/836833645402438850
https://www.figma.com/community/file/836835062056249539
https://www.figma.com/community/file/836828295772957889

I think this should be replaced with [https://www.microsoft.com/design/fluent/](https://www.microsoft.com/design/fluent/) or something like that.

Thank you!

**Comment by misolori** [comment]
Thanks for the info, I've passed along this to the Fluent team.
